name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  isar: 3.0.5
  core: 
    path: ../core/
  dartz: ^0.10.1
  

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
