name: core
description: core package for Jebud, contains domain logic and driver ports.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  collection: ^1.17.1
  equatable: ^2.0.5 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
